### ISSUE TITLE
Submodule lib/closure-library fails and it doesn't work!

### ISSUE THREAD

**Issue by geekdenz** [fivetran/typescript-closure-tools#13]
```
node definition-generator/src/main.js test/example.js test/example.d.ts
fs.js:500
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'test/example.js'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at symbols (/home/heuert/projects/landcare/typescript-closure-tools/definition-generator/src/finder.js:29:68)
    at /home/heuert/projects/landcare/typescript-closure-tools/definition-generator/src/finder.js:69:21
    at Array.forEach (native)
    at Object.<anonymous> (/home/heuert/projects/landcare/typescript-closure-tools/definition-generator/src/finder.js:68:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
after
```
git submodule update
fatal: reference is not a tree: 5e768242074cfdf37965935db5c584d1f96b8563
Unable to checkout '5e768242074cfdf37965935db5c584d1f96b8563' in submodule path 'lib/closure-library'
```

Please fix this as it doesn't work at all at the moment.

**Comment by buenjybar** [comment]
would be great to see a functional version of this tool ..

**Comment by georgewfraser** [comment]
Fixed
